[default]
duration = "30m"
mode = "center"
sorting = "ascending"
queue-size = 100
exec = "~/.config/wpaperd/call-hellwal.sh"

[any]
path = "~/Pictures/Wallpapers"

# [default.transition.book-flip]
# [default.transition.bounce]
# [default.transition.bow-tie-horizontal]
# [default.transition.bow-tie-vertical]
# [default.transition.butterfly-wave-scrawler]
# [default.transition.circle]
# [default.transition.circle-crop]
# [default.transition.circle-open]
# [default.transition.colour-distance]
# [default.transition.cross-wrap]
# [default.transition.cross-zoom]
# [default.transition.directional]
# [default.transition.directional-scaled]
# [default.transition.directional-wipe]
# [default.transition.disolve]
[default.transition.doom]
# [default.transition.doorway]
# [default.transition.dreamy]
# [default.transition.dreamy-zoom]
# [default.transition.edge]
# [default.transition.fade]
# [default.transition.film-burn]
# [default.transition.glitch-displaced]
# [default.transition.glitch-memories]
# [default.transition.grid-flip]
# [default.transition.hexagonize]
# [default.transition.horizontal-close]
# [default.transition.horizontal-open]
# [default.transition.inverted-page-curl]
# [default.transition.left-right]
# [default.transition.linear-blur]
# [default.transition.mosaic]
# [default.transition.overexposuree]
# [default.transition.pixelize]
# [default.transition.polkan-dots-curtain]
# [default.transition.radial]
# [default.transition.rectangle]
# [default.transition.ripple]
# [default.transition.rolls]
# [default.transition.rotate-scale-fade]
# [default.transition.rotate-scale-vanish]
# [default.transition.simple-zoom]
# [default.transition.slides]
# [default.transition.static-fade]
# [default.transition.stereo-viewer]
# [default.transition.swirl]
# [default.transition.water-drop]
# [default.transition.window-blinds]
